apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlFXeGxlR0Z1WkdWeVRVRlVTVHBuYUhCZmNWRmFOVXA2YzI1c1RYSjBhekJ2ZFVOdWVYQnZiR0Z2U0VkRGJVZEdNbXR3ZDNWRiIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
